# Generated by Django 4.2 on 2026-02-28 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ai_chat', 'AI Chat'), ('video', 'Video'), ('in_person', 'In Person'), ('async_chat', 'Async Chat')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('queue_position', models.IntegerField(blank=True, null=True)),
                ('triage_level', models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('agora_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='users.patient')),
            ],
            options={
                'db_table': 'health_consultation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('ai', 'AI')], max_length=10)),
                ('sender_id', models.UUIDField(blank=True, null=True)),
                ('content', models.TextField()),
                ('content_en', models.TextField(blank=True, null=True)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('image', 'Image')], default='text', max_length=10)),
                ('is_triage_result', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.consultation')),
            ],
            options={
                'db_table': 'health_message',
            },
        ),
    ]
