# Generated by Django 4.2 on 2026-02-28 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('brand_names', models.TextField(blank=True, null=True)),
                ('drug_class', models.CharField(blank=True, max_length=100, null=True)),
                ('uses_en', models.TextField()),
                ('dosage_json', models.TextField(blank=True, null=True)),
                ('side_effects_en', models.TextField(blank=True, null=True)),
                ('warnings_en', models.TextField(blank=True, null=True)),
                ('interactions', models.TextField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, max_length=5, null=True)),
                ('jan_aushadhi', models.BooleanField(default=False)),
                ('price_min_paise', models.IntegerField(blank=True, null=True)),
                ('price_max_paise', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicine_drug',
            },
        ),
        migrations.CreateModel(
            name='ClinicStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_qty', models.IntegerField()),
                ('min_threshold', models.IntegerField()),
                ('avg_daily_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('predicted_stockout', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='users.clinic')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='medicines.drug')),
            ],
            options={
                'db_table': 'clinic_stock',
            },
        ),
    ]
